server {
    listen 80;
    server_name scanme.hacknology-lab.local;

    add_header X-Training-Flag "HACKNOLOGY{CUSTOM_HEADER_LEAK}" always;
    add_header X-Powered-By "Hacknology-Training-Lab" always;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /flag.txt {
        return 200 "HACKNOLOGY{HTTP_VERSION_ENUM}\n";
        add_header Content-Type text/plain;
    }
}
